language: ruby

os:
  - linux
  - osx
  - windows

before_install:
 - date -u
 - uname -a
 - env | sort

rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head

script: "./tests/run.sh"

notifications:
 email:
  - vadv.mkn@gmail.com
