language: ruby

os:
  - linux
  - osx
  - windows

before_install:
 - date -u
 - uname -a
 - env | sort

rvm: 
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 1.8.7

script: "./tests/run.sh"

notifications:
 email:
  - vadv.mkn@gmail.com
